### ISSUE TITLE
Synchronizing with Network

### ISSUE THREAD

**Issue by busyforgod** [BitProfile/Xeth#37]
The wallet says that synchronization may take a few minutes. It's been hours and the "Synchronizing with network" bar is only 2/3 full. What should I do?

**Comment by devktor** [comment]
Thank you for reporting it.

Blockchain is quite big now, is normal to take that much time. We need to remove message saying that it takes few minutes, its misleading.

**Comment by busyforgod** [comment]
Four days later & Xeth wallet still hasn't synced with the network & only
one of the two sync arrows is lit up. I tried uninstalling & reinstalling
the wallet but it opened with the sync progress bar in the same spot

**Comment by devktor** [comment]
Ok, lets debug.
Please tell me what operating system do you have (Windows, OSX, Linux) ?

**Comment by busyforgod** [comment]
Windows 8.1 Pro

**Comment by devktor** [comment]
While xeth wallet is running, open [cmd](http://www.digitalcitizen.life/7-ways-launch-command-prompt-windows-7-windows-8) and attach to geth process using the following commands: 

```
cd c:
cd "Program Files\XETH\vendor\bin"
geth attach
```

in geth console, check peers count 

```
web3.net.peerCount
```

then check blockchain size (repeat it several times to see if its progressing)

```
web3.eth.blockNumber
```

**Comment by gonzccs** [comment]
Still having a LOT of truble syncing the network... I also have more than 3 days. And sent some ETH to my wallet, and it is not showing any balance received. Please Help!

Using Windows 10 on a 64Bits platform.

Xeth v.0.4-2 (beta)

Lock sign on green and closed, Network Sign 3 bars with 15 peers, sync sign with only one arrow on no blinking or showing any sign of progress or work, Progress bar totally stuck at around 50% and rolling over the sync sign shows "Last block: 1915292"

the wallet address:

0xf6Bb4cb730D87B6471F83fF3f982ddDD82E65659

**Comment by devktor** [comment]
I see that you have 1.39 ETH on your address. You'll be able to see/spend your ethers once you'll have your wallet synchronized.


Please tell me if "last block" is changing, or it is stuck at 1915292 ? Also please check if you have enough disk space on C:/ partition.

**Comment by gonzccs** [comment]
Hello @devktor .. 

Well after you said that I should check if the "last block" was stuck... I noticed that it was not, slowly going thru... Now I´m at block 2391080, So it took 4 days to get roughly four hundred thousand blocks... 

The thing is that 8 hours ago it was at block 23901079, so only one block in the last eight hours. 

Also, when I look at the system monitor in the tasks manager, I can see "parity.exe" growing in memory usage by the exact rate of the network downloading speed, which makes me think that it is working. Now at something between 1,5mbps to 2,3mbps. The "parity.exe" process takes sometimes up to 1300Mb of memory and makes the PC unusable for long periods of time. 

Please tell me if this is normal, and if there is´nt any other way to get around this. 

By the way, in the file explorer the parity folder measures 37.7GB, Am I too far away from the end of the entire blockchain size?

**Comment by devktor** [comment]
Its not normal. It should be much faster, on my machine it took several hours to fully synchronize. 

My .parity folder is around 120GB, so you are quite far from entire blockchain. 
Can you try to refresh your peers? Just remove parity/network directory but don't forget to backup it first. Eventually you can try to upgrade parity client


I'm working on a release that will work with light clients, so synchronization will be really quick. We should have it in alpha in around one week.
