### ISSUE TITLE
Help on installing / building

### ISSUE THREAD

**Issue by ghost** [BitProfile/Xeth#38]
Hi @devktor @unvoo ,

I'm very new to coding and such and was interested how your beautiful wallet works. However, I tried following your instructions but it didn't work and gave me a headache for a couple of hours. If anyone could give detailed instructions or even better a video on how to view and edit the code and then build it again I would be happy to donate Bitcoins to anyone who helps.

Thanks in advance,

Eddie
- I'm running a Windows machine and I have everything that's required

**Comment by devktor** [comment]
Thank you for reporting it. We are working on a new release that should be ready within next few days. We'll review/improve documentation then.

**Comment by ghost** [comment]
@devktor Great, thanks. If I manage to get it working after your new instructions I'll definitely donate a fair amount.

Thanks Again,

Eddie
