### ISSUE TITLE
what happened to my Mist wallet FFS?

### ISSUE THREAD

**Issue by newmzy** [BitProfile/Xeth#40]
I installed your wallet because I was curious (windows 10). It started syncing, which I thought was weird because I already have the geth and parity nodes installed - why can't it use an existing blockchain?

Then to my disgust, the next time I ran the Mist wallet (using Parity in geth mode) it started syncing from the first block again! 

Why the hell does your wallet interfere with any other wallets on my machine?

**Comment by devktor** [comment]
Parity  has blockchain pruning enabled by default but Xeth needs full chain to be able to scan stealth transactions. So it uses --pruning=archive flag which most probably resets your chain data.

**Comment by devktor** [comment]
In latest release you can switch back to GETH. So you don't need to download entire blockchain again. 

Give it a try.
