### ISSUE TITLE
not enough funds

### ISSUE THREAD

**Issue by daniel67014** [BitProfile/Xeth#43]
I have 5 Ether in Xeth
I cannot send Ether to another address "not enough funds"
I downloaded ethereum wallet and it shows 0 Ether for the same address showing 5 in Xeth
I presumably got this 5 Ether from my first day of mining, but now I'm starting to think I don't have anything.

Does anyone have this problem or know what's happened?

Thank you for your time

Daniel

![xeth problem1](https://cloud.githubusercontent.com/assets/28690311/26036635/03820782-38d9-11e7-96f3-017cc7689ef5.png)
![xeth problem2](https://cloud.githubusercontent.com/assets/28690311/26036637/038387c4-38d9-11e7-8294-83b7f468a80b.png)
![xeth problem3](https://cloud.githubusercontent.com/assets/28690311/26036636/0382d450-38d9-11e7-994b-4797bb83ba9d.png)

**Comment by devktor** [comment]
It shows that you have unconfirmed balance (red color). Maybe you had some transaction or block that never got confirmed. You can try to resync your wallet.
