### ISSUE TITLE
Xeth not syncing

### ISSUE THREAD

**Issue by mecheng9746** [BitProfile/Xeth#44]
Is anyone else having an issue with Xeth taking forever to sync?
I had it running for 1.5 week, got to 243XXXX and then would not connect to peers.
I've uninstalled/deleted blockchain, reinstalled and has now been running for 5 day. Its currently at 242XXXX and moving real slow.........adding 1-5 block/hr
I had ether sent to this wallet before it was synced and cannot see it. Getting very frustrated.

Am i doing something wrong?
Is there a way to migrate this private key to another wallet?

Chris

**Comment by devktor** [comment]
You can try to delete cached peers. Please tell me what OS you have and I'll give you full path.

You can export your keys, check in settings -> backup key.
Also XETH has private keys in the same place as Mist. So, if you want to use Mist, you don't have to do anything, it should see your keys by default.

**Comment by mecheng9746** [comment]
Thank you for the prompt response.
I utilized the backup from XETH and have move this over to Parity. Everything is looking up.
