### ISSUE TITLE
Can't send funds or export wallet

### ISSUE THREAD

**Issue by hunterst44** [BitProfile/Xeth#46]
I keep getting password incorrect errors when I try to send funds. I am certain that my password is correct. If I try to change passwords it accepts the password I have. After though it won't accept either new or old passwords to send funds.

I created a new address and was extra careful with the password. I exported my key and imported into XETH on another machine. It told me the password was incorrect again. 

Is XETH corrupting passwords? If so can I recover my account?

**Comment by hunterst44** [comment]
I have been playing around with myetherwallet and a parity installation on another machine, and I can't get any addresses generated by XETH to import into either of these places. I am using the keystore files generated in /home/.ethereum. (I'm using ubuntu 16.04), and multiple addresses with different passwords.

**Comment by devktor** [comment]
OK, let's debug it. Can we have a chat on tox ( http://tox.chat ) ? my id : 010F55D52420781D04329D2CBEA817AC55D2B3E6085D7B610F888962B699BE158A4F24BA8D66

**Comment by hunterst44** [comment]
Thanks for your quick help. The issue is resolved now.
