### ISSUE TITLE
after loading key doesn't show eth amount

### ISSUE THREAD

**Issue by ghost** [BitProfile/Xeth#55]
re-imported key contained in ..\AppData\Roaming\Xeth\keys, password was accepted, however, address no longer looks correct and no amount is showing for eth amount.

**Comment by devktor** [comment]
Is your wallet synchronized? It may take a while to download the blockchain.

..\AppData\Roaming\Xeth\keys contains only stealth keys. Please check also ..\AppData\Roaming\Ethereum\keystore

**Comment by asamrae2y** [comment]
@devktor thanks for your reply. for some reason, the blockchain has stopped at a certain point and is not completing. 

The weird thing is the key disappeared from \AppData\Roaming\Ethereum\keystore I was expecting UTC--blah but it wasn't there.

So this is what I did:

1. I tried re-creating the key (manually) using the stealth key parameters. 
2. Re-loaded newly created key
3. entered password

Xeth accepted the wallet and shows my Ethereum address, however, blockchain still doesn't complete and when I try to send coin to another address, it says my wallet has zero coin.

My gut feeling is the newly created key is not correct as I tried uploading it to MyEtherWallet.com and it didn't show the correct address associated to it.

Any help would be much appreciated

**Comment by ghost** [comment]
@devktor thanks for your reply. for some reason, the blockchain has stopped at a certain point and is not completing.

The weird thing is the key disappeared from \AppData\Roaming\Ethereum\keystore I was expecting UTC--blah but it wasn't there.

So this is what I did:

1. I tried re-creating the key (manually) using the stealth key parameters.
2. Re-loaded newly created key
3. entered password

Xeth accepted the wallet and shows my Ethereum address, however, blockchain still doesn't complete and when I try to send coin to another address, it says my wallet has zero coin.

My gut feeling is the newly created key is not correct as I tried uploading it to MyEtherWallet.com and it didn't show the correct address associated to it.

Any help would be much appreciated

**Comment by ghost** [comment]
@devktor so I did some analysis today. I generated a new stealth key and it never generated a UTC key in ..\AppData\Roaming\Ethereum\keystore

Am I correct that if you choose the stealth option that a private key (as in the UTC) is not generated?

Nevertheless, it seems like the sync is stuck as I've left the computer on for a few days with no luck.

Here are a few screenshots:
Send window, does not show my wallet address anymore:

![image](https://user-images.githubusercontent.com/33530039/34739553-89fed4cc-f574-11e7-977d-a8bee87361ab.png)

Receive window shows the stealth address:

![image](https://user-images.githubusercontent.com/33530039/34739624-c782dd34-f574-11e7-80c5-0dec5d279269.png)

**Comment by devktor** [comment]
Can we have a chat tomorrow to debug it? 
Meanwhile I'll make a simple script to reveal stealth payments.

**Comment by devktor** [comment]
we can use [tox](https://tox.chat/)

here's my address: 4DFAC7B4632E4FF0E07F84DC0BCA48F69805058050B3FEDA7F559A683448572A1554D976F89E

**Comment by ghost** [comment]
Thank you, what time will you be available?

**Comment by devktor** [comment]
A key resulted from a stealth payment is generated only when it is used. Before that Xeth stores only the shared secret data.  

I made an application to generate that key manually. Please switch to develop branch and build it.

```
make reveal
```

then use it as following:
```
reveal.exe --stealth=stealth_address --address=eth_receiver_address -password=stealth_key_password
```
or if stealth payment wasn't yet uncovered by Xeth then
```
reveal.exe --stealth=stealth_address --address=eth_receiver_address -password=stealth_key_password --ephem=ephem_pubkey_hex
```


I'm online on tox, please ping me when you can.

**Comment by ghost** [comment]
I'm getting the following error when trying to build:

![image](https://user-images.githubusercontent.com/33530039/34955392-10b7c860-fa1c-11e7-93d9-e72fea510d9b.png)

seems like theres some missing files in `Xeth/cmake/modules`

**Comment by devktor** [comment]
you need to pull all submodules :
``` 
git clone --recursive https://github.com/Xeth/Xeth.git
```

**Comment by ghost** [comment]
so i did the following:

1. deleted the previous Xeth reop
2. `git clone --recursive https://github.com/Xeth/Xeth.git` 
3. `git fetch` `git checkout develop` `git pull --rebase origin develop` - just to make sure i've got everything on this branch
4. `cmake -DCRYPTOPP_INCLUDE_DIR=/tmp/xeth_deps -DCRYPTOPP_LIBRARY=/tmp/xeth_deps/cryptopp/libcryptopp.a ..`

after performing step 4, i get:

```
samranator@samranator-VirtualBox:/tmp/Xeth/build$ cmake -DCRYPTOPP_INCLUDE_DIR=/tmp/xeth_deps -DCRYPTOPP_LIBRARY=/tmp/xeth_deps/cryptopp/libcryptopp.a ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:

    /tmp/Xeth/cmake/modules/QRC.cmake


CMake Error at CMakeLists.txt:17 (include):
  include could not find load file:

    /tmp/Xeth/cmake/modules/Test.cmake


-- Check size of void*
-- Check size of void* - done
x86_64 detected
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of int128_t
-- Check size of int128_t - failed
-- Performing Test HAS_FSTACK_PROTECTOR
-- Performing Test HAS_FSTACK_PROTECTOR - Success
-- Performing Test HAS_RELRO
-- Performing Test HAS_RELRO - Failed
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Found JsonCPP: /usr/include/jsoncpp  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
--   random
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Boost version: 1.58.0
-- Check size of int64_t
-- Check size of int64_t - done
StatusLinuxOSdetected
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find EthCrypto (missing: ETHCRYPTO_INCLUDE_DIR ETHCRYPTO_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindEthCrypto.cmake:45 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libethstealth/cmake/lib.cmake:2 (find_package)
  libethstealth/CMakeLists.txt:12 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/Xeth/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/Xeth/build/CMakeFiles/CMakeError.log".

```

**Comment by devktor** [comment]
git clone --recursive https://github.com/Xeth/Xeth.git -b develop

**Comment by ghost** [comment]
```
---------------------------------- target is include_scripts
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'appindicator-0.1'
--   Found appindicator-0.1, version 12.10.0
-- Found APPINDICATOR: /usr/lib/x86_64-linux-gnu/libappindicator.so  
-- Found GTK2_GTK: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so  
-- Found LibNotify: /usr/include/libnotify  
libnotify support enabled
gtk support enabled
appindicator support enabled
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   random
--   regex
--   date_time
--   chrono
--   atomic
leveldblibraries /usr/lib/x86_64-linux-gnu/libleveldb.so
-- Could NOT find GMP (missing:  GMP_INCLUDE_DIR GMP_LIBRARIES) 
-- Configuring incomplete, errors occurred!
See also "/tmp/Xeth/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/Xeth/build/CMakeFiles/CMakeError.log".
```
got that this time.  GBP seems to be missing.

**Comment by ghost** [comment]
actually, this is what happened during the git clone:

```Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
Submodule path 'libethcrypto/cmake/modules': checked out '303c9a67a9e78b97f0dd6796e724a62318213f8a'
Cloning into 'cryptopp'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:weidai11/cryptopp.git' into submodule path 'cryptopp' failed
Failed to recurse into submodule path 'libethcrypto'
```
i tried `sudo git clone --recursive https://github.com/Xeth/Xeth.git -b develop`

could be fixed by adding my public key to your github?

**Comment by devktor** [comment]
yep

**Comment by ghost** [comment]
This is not resolved.

**Comment by devktor** [comment]
This is not a XETH issue, your wallet is not synchronized. You can open other tickets for further issues that you'll find.

**Comment by ghost** [comment]
fair enough.
